/**
 * generated by Xtext 2.23.0
 */
package com.shark.lang.dd.impl;

import com.shark.lang.dd.CheckExpression;
import com.shark.lang.dd.Constraint;
import com.shark.lang.dd.DdPackage;
import com.shark.lang.dd.LineComment;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Constraint</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.shark.lang.dd.impl.ConstraintImpl#getChkDescLines <em>Chk Desc Lines</em>}</li>
 *   <li>{@link com.shark.lang.dd.impl.ConstraintImpl#getName <em>Name</em>}</li>
 *   <li>{@link com.shark.lang.dd.impl.ConstraintImpl#getCheck <em>Check</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ConstraintImpl extends MinimalEObjectImpl.Container implements Constraint
{
  /**
   * The cached value of the '{@link #getChkDescLines() <em>Chk Desc Lines</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getChkDescLines()
   * @generated
   * @ordered
   */
  protected EList<LineComment> chkDescLines;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getCheck() <em>Check</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCheck()
   * @generated
   * @ordered
   */
  protected EList<CheckExpression> check;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConstraintImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DdPackage.Literals.CONSTRAINT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<LineComment> getChkDescLines()
  {
    if (chkDescLines == null)
    {
      chkDescLines = new EObjectContainmentEList<LineComment>(LineComment.class, this, DdPackage.CONSTRAINT__CHK_DESC_LINES);
    }
    return chkDescLines;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DdPackage.CONSTRAINT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<CheckExpression> getCheck()
  {
    if (check == null)
    {
      check = new EObjectContainmentEList<CheckExpression>(CheckExpression.class, this, DdPackage.CONSTRAINT__CHECK);
    }
    return check;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DdPackage.CONSTRAINT__CHK_DESC_LINES:
        return ((InternalEList<?>)getChkDescLines()).basicRemove(otherEnd, msgs);
      case DdPackage.CONSTRAINT__CHECK:
        return ((InternalEList<?>)getCheck()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DdPackage.CONSTRAINT__CHK_DESC_LINES:
        return getChkDescLines();
      case DdPackage.CONSTRAINT__NAME:
        return getName();
      case DdPackage.CONSTRAINT__CHECK:
        return getCheck();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DdPackage.CONSTRAINT__CHK_DESC_LINES:
        getChkDescLines().clear();
        getChkDescLines().addAll((Collection<? extends LineComment>)newValue);
        return;
      case DdPackage.CONSTRAINT__NAME:
        setName((String)newValue);
        return;
      case DdPackage.CONSTRAINT__CHECK:
        getCheck().clear();
        getCheck().addAll((Collection<? extends CheckExpression>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DdPackage.CONSTRAINT__CHK_DESC_LINES:
        getChkDescLines().clear();
        return;
      case DdPackage.CONSTRAINT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case DdPackage.CONSTRAINT__CHECK:
        getCheck().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DdPackage.CONSTRAINT__CHK_DESC_LINES:
        return chkDescLines != null && !chkDescLines.isEmpty();
      case DdPackage.CONSTRAINT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case DdPackage.CONSTRAINT__CHECK:
        return check != null && !check.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ConstraintImpl
