/**
 * generated by Xtext 2.23.0
 */
package com.shark.lang.dd.impl;

import com.shark.lang.dd.DdPackage;
import com.shark.lang.dd.TrailComment;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Trail Comment</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TrailCommentImpl extends MinimalEObjectImpl.Container implements TrailComment
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TrailCommentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DdPackage.Literals.TRAIL_COMMENT;
  }

} //TrailCommentImpl
