/*
 * generated by Xtext 2.23.0
 */
package com.shark.lang.parser.antlr;

import com.google.inject.Inject;
import com.shark.lang.parser.antlr.internal.InternalDdParser;
import com.shark.lang.services.DdGrammarAccess;
import org.antlr.runtime.CharStream;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DdParser extends AbstractAntlrParser {

	@Inject
	private DdGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_CONT", "RULE_IDENT");
	}
	
	@Override
	protected TokenSource createLexer(CharStream stream) {
		return new DdTokenSource(super.createLexer(stream));
	}
	
	/**
	 * Indentation aware languages do not support partial parsing since the lexer is inherently stateful.
	 * Override and return {@code true} if your terminal splitting is stateless.
	 */
	@Override
	protected boolean isReparseSupported() {
		return false;
	}

	@Override
	protected InternalDdParser createParser(XtextTokenStream stream) {
		return new InternalDdParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DataModelFragment";
	}

	public DdGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DdGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
