/**
 * generated by Xtext 2.23.0
 */
package com.shark.lang.dd;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute Size</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.shark.lang.dd.AttributeSize#getLength <em>Length</em>}</li>
 *   <li>{@link com.shark.lang.dd.AttributeSize#getPrecision <em>Precision</em>}</li>
 * </ul>
 *
 * @see com.shark.lang.dd.DdPackage#getAttributeSize()
 * @model
 * @generated
 */
public interface AttributeSize extends EObject
{
  /**
   * Returns the value of the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Length</em>' attribute.
   * @see #setLength(int)
   * @see com.shark.lang.dd.DdPackage#getAttributeSize_Length()
   * @model
   * @generated
   */
  int getLength();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.AttributeSize#getLength <em>Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Length</em>' attribute.
   * @see #getLength()
   * @generated
   */
  void setLength(int value);

  /**
   * Returns the value of the '<em><b>Precision</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Precision</em>' attribute.
   * @see #setPrecision(int)
   * @see com.shark.lang.dd.DdPackage#getAttributeSize_Precision()
   * @model
   * @generated
   */
  int getPrecision();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.AttributeSize#getPrecision <em>Precision</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Precision</em>' attribute.
   * @see #getPrecision()
   * @generated
   */
  void setPrecision(int value);

} // AttributeSize
