/**
 * generated by Xtext 2.23.0
 */
package com.shark.lang.dd;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cat Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.shark.lang.dd.CatExpression#getLeft <em>Left</em>}</li>
 *   <li>{@link com.shark.lang.dd.CatExpression#getOp <em>Op</em>}</li>
 *   <li>{@link com.shark.lang.dd.CatExpression#getRight <em>Right</em>}</li>
 *   <li>{@link com.shark.lang.dd.CatExpression#getCatElts <em>Cat Elts</em>}</li>
 *   <li>{@link com.shark.lang.dd.CatExpression#isChecked <em>Checked</em>}</li>
 * </ul>
 *
 * @see com.shark.lang.dd.DdPackage#getCatExpression()
 * @model
 * @generated
 */
public interface CatExpression extends SharkExpression
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(SharkExpression)
   * @see com.shark.lang.dd.DdPackage#getCatExpression_Left()
   * @model containment="true"
   * @generated
   */
  SharkExpression getLeft();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.CatExpression#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(SharkExpression value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see com.shark.lang.dd.DdPackage#getCatExpression_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.CatExpression#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(SharkExpression)
   * @see com.shark.lang.dd.DdPackage#getCatExpression_Right()
   * @model containment="true"
   * @generated
   */
  SharkExpression getRight();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.CatExpression#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(SharkExpression value);

  /**
   * Returns the value of the '<em><b>Cat Elts</b></em>' containment reference list.
   * The list contents are of type {@link com.shark.lang.dd.CatExpressionElt}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cat Elts</em>' containment reference list.
   * @see com.shark.lang.dd.DdPackage#getCatExpression_CatElts()
   * @model containment="true"
   * @generated
   */
  EList<CatExpressionElt> getCatElts();

  /**
   * Returns the value of the '<em><b>Checked</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Checked</em>' attribute.
   * @see #setChecked(boolean)
   * @see com.shark.lang.dd.DdPackage#getCatExpression_Checked()
   * @model
   * @generated
   */
  boolean isChecked();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.CatExpression#isChecked <em>Checked</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Checked</em>' attribute.
   * @see #isChecked()
   * @generated
   */
  void setChecked(boolean value);

} // CatExpression
