/**
 * generated by Xtext 2.23.0
 */
package com.shark.lang.dd;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.shark.lang.dd.Constraint#getChkDescLines <em>Chk Desc Lines</em>}</li>
 *   <li>{@link com.shark.lang.dd.Constraint#getName <em>Name</em>}</li>
 *   <li>{@link com.shark.lang.dd.Constraint#getCheck <em>Check</em>}</li>
 * </ul>
 *
 * @see com.shark.lang.dd.DdPackage#getConstraint()
 * @model
 * @generated
 */
public interface Constraint extends EObject
{
  /**
   * Returns the value of the '<em><b>Chk Desc Lines</b></em>' containment reference list.
   * The list contents are of type {@link com.shark.lang.dd.LineComment}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Chk Desc Lines</em>' containment reference list.
   * @see com.shark.lang.dd.DdPackage#getConstraint_ChkDescLines()
   * @model containment="true"
   * @generated
   */
  EList<LineComment> getChkDescLines();

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.shark.lang.dd.DdPackage#getConstraint_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.Constraint#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Check</b></em>' containment reference list.
   * The list contents are of type {@link com.shark.lang.dd.CheckExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Check</em>' containment reference list.
   * @see com.shark.lang.dd.DdPackage#getConstraint_Check()
   * @model containment="true"
   * @generated
   */
  EList<CheckExpression> getCheck();

} // Constraint
