/**
 * generated by Xtext 2.23.0
 */
package com.shark.lang.dd;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.shark.lang.dd.Constant#getExtraAttrDesc <em>Extra Attr Desc</em>}</li>
 *   <li>{@link com.shark.lang.dd.Constant#getDataType <em>Data Type</em>}</li>
 *   <li>{@link com.shark.lang.dd.Constant#getAttributeSize <em>Attribute Size</em>}</li>
 *   <li>{@link com.shark.lang.dd.Constant#getArraySize <em>Array Size</em>}</li>
 *   <li>{@link com.shark.lang.dd.Constant#getName <em>Name</em>}</li>
 *   <li>{@link com.shark.lang.dd.Constant#getDefaultValue <em>Default Value</em>}</li>
 *   <li>{@link com.shark.lang.dd.Constant#getAttrDesc <em>Attr Desc</em>}</li>
 * </ul>
 *
 * @see com.shark.lang.dd.DdPackage#getConstant()
 * @model
 * @generated
 */
public interface Constant extends EObject
{
  /**
   * Returns the value of the '<em><b>Extra Attr Desc</b></em>' containment reference list.
   * The list contents are of type {@link com.shark.lang.dd.LineComment}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extra Attr Desc</em>' containment reference list.
   * @see com.shark.lang.dd.DdPackage#getConstant_ExtraAttrDesc()
   * @model containment="true"
   * @generated
   */
  EList<LineComment> getExtraAttrDesc();

  /**
   * Returns the value of the '<em><b>Data Type</b></em>' attribute.
   * The literals are from the enumeration {@link com.shark.lang.dd.DataType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Type</em>' attribute.
   * @see com.shark.lang.dd.DataType
   * @see #setDataType(DataType)
   * @see com.shark.lang.dd.DdPackage#getConstant_DataType()
   * @model
   * @generated
   */
  DataType getDataType();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.Constant#getDataType <em>Data Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data Type</em>' attribute.
   * @see com.shark.lang.dd.DataType
   * @see #getDataType()
   * @generated
   */
  void setDataType(DataType value);

  /**
   * Returns the value of the '<em><b>Attribute Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute Size</em>' containment reference.
   * @see #setAttributeSize(AttributeSize)
   * @see com.shark.lang.dd.DdPackage#getConstant_AttributeSize()
   * @model containment="true"
   * @generated
   */
  AttributeSize getAttributeSize();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.Constant#getAttributeSize <em>Attribute Size</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute Size</em>' containment reference.
   * @see #getAttributeSize()
   * @generated
   */
  void setAttributeSize(AttributeSize value);

  /**
   * Returns the value of the '<em><b>Array Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array Size</em>' containment reference.
   * @see #setArraySize(ArraySize)
   * @see com.shark.lang.dd.DdPackage#getConstant_ArraySize()
   * @model containment="true"
   * @generated
   */
  ArraySize getArraySize();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.Constant#getArraySize <em>Array Size</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Array Size</em>' containment reference.
   * @see #getArraySize()
   * @generated
   */
  void setArraySize(ArraySize value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.shark.lang.dd.DdPackage#getConstant_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.Constant#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Default Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default Value</em>' containment reference.
   * @see #setDefaultValue(SharkExpression)
   * @see com.shark.lang.dd.DdPackage#getConstant_DefaultValue()
   * @model containment="true"
   * @generated
   */
  SharkExpression getDefaultValue();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.Constant#getDefaultValue <em>Default Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default Value</em>' containment reference.
   * @see #getDefaultValue()
   * @generated
   */
  void setDefaultValue(SharkExpression value);

  /**
   * Returns the value of the '<em><b>Attr Desc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attr Desc</em>' containment reference.
   * @see #setAttrDesc(TrailComment)
   * @see com.shark.lang.dd.DdPackage#getConstant_AttrDesc()
   * @model containment="true"
   * @generated
   */
  TrailComment getAttrDesc();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.Constant#getAttrDesc <em>Attr Desc</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attr Desc</em>' containment reference.
   * @see #getAttrDesc()
   * @generated
   */
  void setAttrDesc(TrailComment value);

} // Constant
