/**
 * generated by Xtext 2.23.0
 */
package com.shark.lang.dd;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.shark.lang.dd.Entity#getEntityDescLines <em>Entity Desc Lines</em>}</li>
 *   <li>{@link com.shark.lang.dd.Entity#getName <em>Name</em>}</li>
 *   <li>{@link com.shark.lang.dd.Entity#getExtends <em>Extends</em>}</li>
 *   <li>{@link com.shark.lang.dd.Entity#getAttributes <em>Attributes</em>}</li>
 *   <li>{@link com.shark.lang.dd.Entity#getRelationships <em>Relationships</em>}</li>
 * </ul>
 *
 * @see com.shark.lang.dd.DdPackage#getEntity()
 * @model
 * @generated
 */
public interface Entity extends EObject
{
  /**
   * Returns the value of the '<em><b>Entity Desc Lines</b></em>' containment reference list.
   * The list contents are of type {@link com.shark.lang.dd.LineComment}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity Desc Lines</em>' containment reference list.
   * @see com.shark.lang.dd.DdPackage#getEntity_EntityDescLines()
   * @model containment="true"
   * @generated
   */
  EList<LineComment> getEntityDescLines();

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.shark.lang.dd.DdPackage#getEntity_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.Entity#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Extends</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extends</em>' reference.
   * @see #setExtends(Entity)
   * @see com.shark.lang.dd.DdPackage#getEntity_Extends()
   * @model
   * @generated
   */
  Entity getExtends();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.Entity#getExtends <em>Extends</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Extends</em>' reference.
   * @see #getExtends()
   * @generated
   */
  void setExtends(Entity value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link com.shark.lang.dd.Attribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see com.shark.lang.dd.DdPackage#getEntity_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

  /**
   * Returns the value of the '<em><b>Relationships</b></em>' containment reference list.
   * The list contents are of type {@link com.shark.lang.dd.Relationship}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relationships</em>' containment reference list.
   * @see com.shark.lang.dd.DdPackage#getEntity_Relationships()
   * @model containment="true"
   * @generated
   */
  EList<Relationship> getRelationships();

} // Entity
