/**
 * generated by Xtext 2.23.0
 */
package com.shark.lang.dd;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relationship</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.shark.lang.dd.Relationship#getCardi1 <em>Cardi1</em>}</li>
 *   <li>{@link com.shark.lang.dd.Relationship#getName <em>Name</em>}</li>
 *   <li>{@link com.shark.lang.dd.Relationship#getCardi2 <em>Cardi2</em>}</li>
 *   <li>{@link com.shark.lang.dd.Relationship#getLinkTo <em>Link To</em>}</li>
 *   <li>{@link com.shark.lang.dd.Relationship#getRelDesc <em>Rel Desc</em>}</li>
 * </ul>
 *
 * @see com.shark.lang.dd.DdPackage#getRelationship()
 * @model
 * @generated
 */
public interface Relationship extends EObject
{
  /**
   * Returns the value of the '<em><b>Cardi1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cardi1</em>' containment reference.
   * @see #setCardi1(ListExpression)
   * @see com.shark.lang.dd.DdPackage#getRelationship_Cardi1()
   * @model containment="true"
   * @generated
   */
  ListExpression getCardi1();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.Relationship#getCardi1 <em>Cardi1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cardi1</em>' containment reference.
   * @see #getCardi1()
   * @generated
   */
  void setCardi1(ListExpression value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.shark.lang.dd.DdPackage#getRelationship_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.Relationship#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Cardi2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cardi2</em>' containment reference.
   * @see #setCardi2(ListExpression)
   * @see com.shark.lang.dd.DdPackage#getRelationship_Cardi2()
   * @model containment="true"
   * @generated
   */
  ListExpression getCardi2();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.Relationship#getCardi2 <em>Cardi2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cardi2</em>' containment reference.
   * @see #getCardi2()
   * @generated
   */
  void setCardi2(ListExpression value);

  /**
   * Returns the value of the '<em><b>Link To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Link To</em>' reference.
   * @see #setLinkTo(Entity)
   * @see com.shark.lang.dd.DdPackage#getRelationship_LinkTo()
   * @model
   * @generated
   */
  Entity getLinkTo();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.Relationship#getLinkTo <em>Link To</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Link To</em>' reference.
   * @see #getLinkTo()
   * @generated
   */
  void setLinkTo(Entity value);

  /**
   * Returns the value of the '<em><b>Rel Desc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rel Desc</em>' containment reference.
   * @see #setRelDesc(TrailComment)
   * @see com.shark.lang.dd.DdPackage#getRelationship_RelDesc()
   * @model containment="true"
   * @generated
   */
  TrailComment getRelDesc();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.Relationship#getRelDesc <em>Rel Desc</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rel Desc</em>' containment reference.
   * @see #getRelDesc()
   * @generated
   */
  void setRelDesc(TrailComment value);

} // Relationship
