/**
 * generated by Xtext 2.23.0
 */
package com.shark.lang.dd;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Str Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.shark.lang.dd.StrValue#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see com.shark.lang.dd.DdPackage#getStrValue()
 * @model
 * @generated
 */
public interface StrValue extends TerminalExpression
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see com.shark.lang.dd.DdPackage#getStrValue_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.StrValue#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // StrValue
