/**
 * generated by Xtext 2.23.0
 */
package com.shark.lang.dd;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Trail Comment</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.shark.lang.dd.DdPackage#getTrailComment()
 * @model
 * @generated
 */
public interface TrailComment extends EObject
{
} // TrailComment
