/**
 * generated by Xtext 2.23.0
 */
package com.shark.lang.dd;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unary Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.shark.lang.dd.UnaryExpression#getOp <em>Op</em>}</li>
 *   <li>{@link com.shark.lang.dd.UnaryExpression#getLeft <em>Left</em>}</li>
 *   <li>{@link com.shark.lang.dd.UnaryExpression#isNumType <em>Num Type</em>}</li>
 *   <li>{@link com.shark.lang.dd.UnaryExpression#isStrType <em>Str Type</em>}</li>
 *   <li>{@link com.shark.lang.dd.UnaryExpression#isDateType <em>Date Type</em>}</li>
 *   <li>{@link com.shark.lang.dd.UnaryExpression#isBoolType <em>Bool Type</em>}</li>
 * </ul>
 *
 * @see com.shark.lang.dd.DdPackage#getUnaryExpression()
 * @model
 * @generated
 */
public interface UnaryExpression extends SharkExpression
{
  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * The literals are from the enumeration {@link com.shark.lang.dd.UnaryOperator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see com.shark.lang.dd.UnaryOperator
   * @see #setOp(UnaryOperator)
   * @see com.shark.lang.dd.DdPackage#getUnaryExpression_Op()
   * @model
   * @generated
   */
  UnaryOperator getOp();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.UnaryExpression#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see com.shark.lang.dd.UnaryOperator
   * @see #getOp()
   * @generated
   */
  void setOp(UnaryOperator value);

  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(SharkExpression)
   * @see com.shark.lang.dd.DdPackage#getUnaryExpression_Left()
   * @model containment="true"
   * @generated
   */
  SharkExpression getLeft();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.UnaryExpression#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(SharkExpression value);

  /**
   * Returns the value of the '<em><b>Num Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num Type</em>' attribute.
   * @see #setNumType(boolean)
   * @see com.shark.lang.dd.DdPackage#getUnaryExpression_NumType()
   * @model
   * @generated
   */
  boolean isNumType();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.UnaryExpression#isNumType <em>Num Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num Type</em>' attribute.
   * @see #isNumType()
   * @generated
   */
  void setNumType(boolean value);

  /**
   * Returns the value of the '<em><b>Str Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Str Type</em>' attribute.
   * @see #setStrType(boolean)
   * @see com.shark.lang.dd.DdPackage#getUnaryExpression_StrType()
   * @model
   * @generated
   */
  boolean isStrType();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.UnaryExpression#isStrType <em>Str Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Str Type</em>' attribute.
   * @see #isStrType()
   * @generated
   */
  void setStrType(boolean value);

  /**
   * Returns the value of the '<em><b>Date Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Date Type</em>' attribute.
   * @see #setDateType(boolean)
   * @see com.shark.lang.dd.DdPackage#getUnaryExpression_DateType()
   * @model
   * @generated
   */
  boolean isDateType();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.UnaryExpression#isDateType <em>Date Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Date Type</em>' attribute.
   * @see #isDateType()
   * @generated
   */
  void setDateType(boolean value);

  /**
   * Returns the value of the '<em><b>Bool Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bool Type</em>' attribute.
   * @see #setBoolType(boolean)
   * @see com.shark.lang.dd.DdPackage#getUnaryExpression_BoolType()
   * @model
   * @generated
   */
  boolean isBoolType();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.UnaryExpression#isBoolType <em>Bool Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bool Type</em>' attribute.
   * @see #isBoolType()
   * @generated
   */
  void setBoolType(boolean value);

} // UnaryExpression
