/**
 * generated by Xtext 2.23.0
 */
package com.shark.lang.dd;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unset Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.shark.lang.dd.UnsetValue#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see com.shark.lang.dd.DdPackage#getUnsetValue()
 * @model
 * @generated
 */
public interface UnsetValue extends TerminalExpression
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * The literals are from the enumeration {@link com.shark.lang.dd.Unset}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see com.shark.lang.dd.Unset
   * @see #setValue(Unset)
   * @see com.shark.lang.dd.DdPackage#getUnsetValue_Value()
   * @model
   * @generated
   */
  Unset getValue();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.UnsetValue#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see com.shark.lang.dd.Unset
   * @see #getValue()
   * @generated
   */
  void setValue(Unset value);

} // UnsetValue
