/*
 * generated by Xtext 2.23.0
 */
package com.shark.lang.ui;

import com.google.inject.Injector;
import com.shark.lang.dd.ui.internal.DdActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DdExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(DdActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		DdActivator activator = DdActivator.getInstance();
		return activator != null ? activator.getInjector(DdActivator.COM_SHARK_LANG_DD) : null;
	}

}
