/*
 * generated by Xtext 2.23.0
 */
package com.shark.lang.ui.tests;

import com.google.inject.Injector;
import com.shark.lang.dd.ui.internal.DdActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class DdUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DdActivator.getInstance().getInjector("com.shark.lang.Dd");
	}

}
