/*
 * generated by Xtext 2.21.0
 */
package com.shark.lang.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class DdWebModule extends AbstractDdWebModule {
}
