/*
 * generated by Xtext 2.23.0
 */
package com.shark.lang.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDdScopeProvider extends DelegatingScopeProvider {
}
