/*
 * generated by Xtext 2.23.0
 */
package com.shark.lang.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link DdWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractDdWebModule extends DefaultWebModule {

}
